// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sferity.Backend.Data;

#nullable disable

namespace Sferity.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506222636_AddActiveFrom")]
    partial class AddActiveFrom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sferity.Backend.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from");

                    b.Property<bool>("AllowLabelRedemption")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_label_redemption");

                    b.Property<Guid>("Code")
                        .HasColumnType("uuid")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("integer")
                        .HasColumnName("credit_amount");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_promo_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_promo_codes_code");

                    b.HasIndex("Label")
                        .HasDatabaseName("ix_promo_codes_label");

                    b.ToTable("promo_codes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
