<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>Sferity.Backend.FinalV2</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <!-- Tylko to, co naprawdę potrzebne do działania Twojego kodu -->
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <PackageReference Include="Google.GenAI" Version="1.0.0" />
        <PackageReference Include="Liquiid.io.AtomicMarket" Version="1.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.20" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.20" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.20" />
        <PackageReference Include="Npgsql" Version="10.0.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2" />
        <PackageReference Include="QRCoder" Version="1.6.0" />
        <PackageReference Include="QuestPDF" Version="2024.12.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
        <PackageReference Include="TimeZoneConverter" Version="6.1.0" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="admin_database.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>